### PR TITLE
Added React version

### PR DESCRIPTION
**Pull request by H-Frederick**

### CODE REVIEW

**Comment by artem-kurchenko** [comment]
@H-Frederick 
The React part looks fine. But I don't understand why we change CSS and JS in JQuery to CDN. We specially use node_modules for CI like in our template: https://github.com/DevExpress-Examples/DevExtreme-Examples-Template
Do I missed anything specific?

**Comment by H-Frederick** [comment]
> Do I missed anything specific?

Oops, I've replaced those links from my fork when I wanted to run the jQuery snippet without npm i... It seems I accidentally committed those changes along with react.

Is there any way to remove the jQuery changes from this PR, or should I just create a new one? @artem-kurchenko

**Comment by artem-kurchenko** [comment]
@H-Frederick If you use some tool like GitHub for Desktop you can make another commit to this PR that rejects these changes:
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit
Or you need to correct these lines in code back and make another commit to this pull request

**Comment by H-Frederick** [comment]
@artem-kurchenko I pushed new changes to this PR. There's no jQuery changes for this one now. Please merge it.

**Pull request merged**
